# global options
set_seeds: False
random_seed: 42

# override this in other yaml files
mode: train
config_name: "train"

# paths etc.
data:

    root: '.'
    data: './data'
    input: './input'
    delimiter: ';'


# metrics related options
# what, save etc.
metrics:

    # where to save metrics
    out_path: "./output"

    # save & overwrite
    save_to_disk: true
    overwrite_last: true



# experiment parameters
experiment:
    name: "testing"
    mongo:
        enable: True
        url: "127.0.0.1"
        db: opm
        use_remote: False
        ip: "0.0.0.0"
        username: "mongodb"
        password: "password"


training:

    # whether to perform validation
    # after N train steps
    validate:
        enable: false
        every_N_iters: 10

    # whether to save the current model
    # after every N train steps
    save_model:
        enable: true
        every_N_iters: 100

testing:
    # test parameters (overwritten from test.yml)
    testing_parameter: 10

# debugging options
debug:

    # config
    config: false

 
